name: go-test

on:
  push:
    tags:
      - v*
    branches:
      - "*"
  pull_request:

jobs:
  gotest:
    name: tests
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install go dependencies
      run: go mod tidy
    - name: Run Go Tests
      run: make test
